"""FastAPI application for AI image detection."""

from contextlib import asynccontextmanager
from io import BytesIO

import httpx
from fastapi import FastAPI, File, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware

from . import __version__
from .detector import analyze_image, analyze_video_frames, get_detector
from .models import (
    AnalysisResponse,
    ErrorResponse,
    HealthResponse,
    VideoAnalysisResponse,
    VideoAnalysisDetailedResponse,
    VideoURLRequest,
)
from .utils import (
    SUPPORTED_CONTENT_TYPES,
    load_image,
    preprocess_image,
    validate_content_type,
)
from .video_processor import (
    SUPPORTED_VIDEO_CONTENT_TYPES,
    MAX_VIDEO_SIZE,
    extract_keyframes_from_bytes,
    validate_video_content_type,
)


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Load the model on startup."""
    # Load model on startup (warmup)
    get_detector()
    yield


app = FastAPI(
    title="AI Image Detector",
    description="API para detectar imagenes generadas por IA",
    version=__version__,
    lifespan=lifespan,
)

# Configure CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/health", response_model=HealthResponse, tags=["Health"])
async def health_check():
    """
    Check the health status of the API.

    Returns the service status, version, and whether the model is loaded.
    """
    detector = get_detector()
    return HealthResponse(
        status="healthy",
        version=__version__,
        model_loaded=detector._classifier is not None,
    )


@app.post(
    "/analyze",
    response_model=AnalysisResponse,
    responses={
        400: {"model": ErrorResponse, "description": "Invalid image"},
        500: {"model": ErrorResponse, "description": "Internal server error"},
    },
    tags=["Analysis"],
)
async def analyze(file: UploadFile = File(..., description="Image file to analyze")):
    """
    Analyze an image to detect if it was generated by AI.

    Upload an image file (JPEG, PNG, WebP, GIF, BMP) and receive
    a confidence score indicating the likelihood of AI generation.

    - **is_ai_generated**: Boolean indicating if detected as AI-generated
    - **confidence**: Score from 0 to 1 (higher = more confident)
    - **label**: Classification label ('ai_generated' or 'human_made')
    - **processing_time_ms**: Time taken to process in milliseconds
    """
    # Validate content type
    if not validate_content_type(file.content_type):
        raise HTTPException(
            status_code=400,
            detail=f"Invalid content type: {file.content_type}. "
            f"Supported types: {', '.join(SUPPORTED_CONTENT_TYPES)}",
        )

    try:
        # Read file content
        content = await file.read()

        # Load and preprocess image
        image = load_image(BytesIO(content))
        image = preprocess_image(image)

        # Analyze image
        result = analyze_image(image)

        return AnalysisResponse(**result)

    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Error processing image: {str(e)}",
        )


@app.post(
    "/analyze/video",
    response_model=VideoAnalysisResponse,
    responses={
        400: {"model": ErrorResponse, "description": "Invalid video"},
        413: {"model": ErrorResponse, "description": "Video too large"},
        500: {"model": ErrorResponse, "description": "Internal server error"},
    },
    tags=["Video Analysis"],
)
async def analyze_video(
    file: UploadFile = File(..., description="Video file to analyze"),
):
    """
    Analyze a video to detect AI manipulation or generation.

    Upload a video file (MP4, WebM, AVI, MOV, MKV) and receive
    a fraud detection verdict.

    - **veracity_score**: 0-100 (100 = authentic, 0 = fake/AI)
    - **fraud_detected**: Boolean indicating if manipulation was detected
    - **confidence**: 0-100 confidence level of the detection
    """
    # Validate content type
    if not validate_video_content_type(file.content_type):
        raise HTTPException(
            status_code=400,
            detail=f"Invalid content type: {file.content_type}. "
            f"Supported types: {', '.join(SUPPORTED_VIDEO_CONTENT_TYPES)}",
        )

    try:
        # Read file content
        content = await file.read()

        # Check file size
        if len(content) > MAX_VIDEO_SIZE:
            raise HTTPException(
                status_code=413,
                detail=f"Video too large. Maximum size: {MAX_VIDEO_SIZE // (1024*1024)}MB",
            )

        # Extract keyframes and get video info
        keyframes, video_info = extract_keyframes_from_bytes(content)

        if not keyframes:
            raise HTTPException(
                status_code=400,
                detail="No keyframes could be extracted from the video",
            )

        # Analyze all frames
        result = analyze_video_frames(
            frames=keyframes,
            video_duration=video_info.get("duration_seconds", 0.0),
            detailed=False,
        )

        return VideoAnalysisResponse(**result)

    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Error processing video: {str(e)}",
        )


@app.post(
    "/analyze/video/url",
    response_model=VideoAnalysisResponse,
    responses={
        400: {"model": ErrorResponse, "description": "Invalid request or video"},
        413: {"model": ErrorResponse, "description": "Video too large"},
        500: {"model": ErrorResponse, "description": "Internal server error"},
        502: {"model": ErrorResponse, "description": "Failed to fetch video from URL"},
    },
    tags=["Video Analysis"],
)
async def analyze_video_from_url(request: VideoURLRequest):
    """
    Analyze a video from an external URL to detect AI manipulation.

    Fetches a video from the provided URL (with optional authorization)
    and analyzes it for AI-generated content.

    **Request body:**
    - **url**: URL to fetch the video from
    - **authorization**: Optional auth header (e.g., "Bearer token123")

    **Response:**
    - **veracity_score**: 0-100 (100 = authentic, 0 = fake/AI)
    - **fraud_detected**: Boolean indicating if manipulation was detected
    - **confidence**: 0-100 confidence level of the detection
    """
    try:
        # Prepare headers
        headers = {}
        if request.authorization:
            headers["Authorization"] = request.authorization

        # Fetch video from URL
        async with httpx.AsyncClient(timeout=60.0) as client:
            response = await client.get(request.url, headers=headers)

            if response.status_code != 200:
                raise HTTPException(
                    status_code=502,
                    detail=f"Failed to fetch video from URL. Status: {response.status_code}",
                )

            content = response.content

        # Check file size
        if len(content) > MAX_VIDEO_SIZE:
            raise HTTPException(
                status_code=413,
                detail=f"Video too large. Maximum size: {MAX_VIDEO_SIZE // (1024*1024)}MB",
            )

        # Extract keyframes and get video info
        keyframes, video_info = extract_keyframes_from_bytes(content)

        if not keyframes:
            raise HTTPException(
                status_code=400,
                detail="No keyframes could be extracted from the video",
            )

        # Analyze all frames
        result = analyze_video_frames(
            frames=keyframes,
            video_duration=video_info.get("duration_seconds", 0.0),
            detailed=False,
        )

        return VideoAnalysisResponse(**result)

    except HTTPException:
        raise
    except httpx.TimeoutException:
        raise HTTPException(
            status_code=502,
            detail="Timeout while fetching video from URL",
        )
    except httpx.RequestError as e:
        raise HTTPException(
            status_code=502,
            detail=f"Error fetching video from URL: {str(e)}",
        )
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Error processing video: {str(e)}",
        )


@app.get("/", tags=["Root"])
async def root():
    """Root endpoint with API information."""
    return {
        "name": "AI Image Detector",
        "version": __version__,
        "docs": "/docs",
        "health": "/health",
    }
